<?php
$template = '<html>
<head debug="true" startOpened="true">
<meta charset="UTF-8"/>
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />
<!--<script src="https://getfirebug.com/firebug-lite-debug.js"></script>-->
<script src="MainXML.js"></script>
<link rel="stylesheet" href="/script/style.css"></link>
<script src="/script/jquery.min.js"></script>
<script src="/script/load.js"></script>
<script src="/script/messyHTML.js"></script>
<script src="/script/mouse.js"></script>
<script src="/script/sequence.js"></script>
<script src="/script/effects.js"></script>
<script src="/script/buffer.js"></script>
<script src="/script/progress.js"></script>
<script src="/script/progress.js"></script>
<script src="/script/saveStates.js"></script>
<script src="/script/dependenciesLoc.js"></script>
<script src="audio/sprite.js"></script>
<script src="images/imgCheck.js"></script>
</head>
<body class="noSelect">
</body>
</html>';
?>
